name: weather_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  dio: ^5.4.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  build_runner: ^2.3.3
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true

  assets:
    - assets/
